### ISSUE TITLE
Further developing this crate?

### ISSUE THREAD

**Issue by rodrigocfd** [andrewhickman/defer#1]
Hi Andrew,

I'm interested in further developing this crate, by turning it into [a macro](https://github.com/rodrigocfd/flac-lame-frontend/blob/rust-v2/src/defer.rs) and writing all the documentation for both GitHub and Crates.io.

Do you consider sharing the ownership of [the crate](https://crates.io/crates/defer)?

Thank you.

**Comment by andrewhickman** [comment]
Hi,

I don't think this crate is actually very useful anymore, its pretty much superseded by [scopeguard](https://crates.io/crates/scopeguard) which has more features (it also provides a defer macro)

However if you'd still like to work on it, I'm happy to accept PRs

**Comment by tmccombs** [comment]
If this create is superseded by scopeguard, would it make sense for it to mention that in the README?

**Comment by berkus** [comment]
> However if you'd still like to work on it, I'm happy to accept PRs

@andrewhickman hi, could you take a look at #2 then?

**Comment by berkus** [comment]
@andrewhickman yet one more update in #3!
